### ISSUE TITLE
Please Backport for 1.12.2

### ISSUE THREAD

**Issue by color-space** [Chaos02/SubFolderLoader#2]
I need this for dynamic mod resolution via symbolic link to self-updating git repositories of mods

**Comment by Chaos02** [comment]
Hey - do you have a repo with your current project so I can take a look at what you are doing?
I'm interested in what you are saying.
Also sorry for the late answer.
In the near future I will start working on this mod again.
I will probably provide support for 1.12.2 and 1.16.5 as those are the major modding versions.

**Comment by Chaos02** [comment]
I am trying to backport my mod to 1.12.2 and 1.16.5 but the MDKs from forge cannot be set up anymore and when asking for help with this on the forge forum I just get told that it's a legacy version ([link](https://forums.minecraftforge.net/topic/114254-1122-geneclipseruns-fails-on-init/)).
Please start running in the doors of forge with me as their support really sucks :/

**Comment by color-space** [comment]
Hey there, can't you download the MDKs for forge from the forge website? What do you mean by setup?

**Comment by Chaos02** [comment]
> Hey there, can't you download the MDKs for forge from the forge website? What do you mean by setup?

to properly use the MDKs you can obtain from the forge website you need to run a few commands which in this case are broken.

**Comment by rvveber** [comment]
Hmm you might find unofficial forge discord servers that will help you. Idk about the issue. How are other devs developing their stuff?

**Comment by Chaos02** [comment]
actually no idea - tho even in 1.16.5 There isn't source code available for the ModDiscoverer which is an essential part of my Mod.
I need to understand how it works first to implement classes for it to load other mods.
So as far as that goes - sadly no backports probably. I know I could decompile this stuff but this is morally questionable and honestly too much work for me to put into legacy versions.
Most of the mods that were on 1.12.2 are currently being developed for 1.18+ so there probably isn't much value in staying on the old versions with new projects.
Good luck with your project tho!

**Comment by Chaos02** [comment]
Hey, I've recieved some information on which java version should be compatible for 1.12 and I've just finished the 1.16.5 port - good chances for 1.12

**Comment by rvveber** [comment]
Wohoo! :)
